// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0535TreFtk4HImhPMRJLAH77PxaTE4GQ',
    appId: '1:1032973035887:web:d1758b58278155e24fa09a',
    messagingSenderId: '1032973035887',
    projectId: 'appturismo-88cf4',
    authDomain: 'appturismo-88cf4.firebaseapp.com',
    storageBucket: 'appturismo-88cf4.appspot.com',
    measurementId: 'G-ZN2PBD7XC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1856aYvMguLCV29DEsJtig4ZuZdP_XPU',
    appId: '1:1032973035887:android:d602d9d0cca6f0774fa09a',
    messagingSenderId: '1032973035887',
    projectId: 'appturismo-88cf4',
    storageBucket: 'appturismo-88cf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqBu4GqZbQcgC5CTGRCg-8NBA9RFoB7Oc',
    appId: '1:1032973035887:ios:042db3573648d99b4fa09a',
    messagingSenderId: '1032973035887',
    projectId: 'appturismo-88cf4',
    storageBucket: 'appturismo-88cf4.appspot.com',
    iosClientId: '1032973035887-44tura6hpbqlf9po7tro2ogtna7r1pqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.nomadasColombia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqBu4GqZbQcgC5CTGRCg-8NBA9RFoB7Oc',
    appId: '1:1032973035887:ios:042db3573648d99b4fa09a',
    messagingSenderId: '1032973035887',
    projectId: 'appturismo-88cf4',
    storageBucket: 'appturismo-88cf4.appspot.com',
    iosClientId: '1032973035887-44tura6hpbqlf9po7tro2ogtna7r1pqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.nomadasColombia',
  );
}
